[tool.poetry]
name = "ansible-k8s"
version = "0.1.0"
description = ""
authors = ["Oswald Gyabaah <oswald.gyabaah@gtbank.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
ansible = "^11.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
