[tool.poetry]
name = "loadtesting"
version = "0.1.0"
description = ""
authors = ["Oswald Gyabaah <oswald.gyabaah@gtbank.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
locust = "^2.32.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
