
services:
  flaskapp:
    image: qclaire/flask-docker-app
    build:
      context: .
      dockerfile: Dockerfile.flaskApp
    ports:
      - 5000:5000
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379

