services:
  flask-app:
    image: flask-broken-docker-app
    build:
      context: .
      dockerfile: Dockerfile.flaskApp
    ports: ["4500:5000"]
    environment:
      - FLASK_APP=flask-app.py
  redis:
    image: redis:alpine