---
- name: Initialize Kubernetes master node
  when: inventory_hostname in groups['masters']
  command: kubeadm init --pod-network-cidr={{ pod_network_cidr }} --kubernetes-version={{ kubernetes_version }}
  register: kubeadm_init

- name: Set up kubeconfig for master node
  shell: |
    mkdir -p $HOME/.kube
    cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    chown $(id -u):$(id -g) $HOME/.kube/config
  when: "'master' in group_names"

- name: Get kubeadm join command
  command: kubeadm token create --print-join-command
  register: kubeadm_join_command
  when: "'master' in group_names"

- name: Save kubeadm join command to file
  copy:
    content: "{{ kubeadm_join_command.stdout }}"
    dest: "/tmp/kubeadm_join_command.txt"
  when: "'master' in group_names"

- name: Install Flannel network on master node
  when: inventory_hostname in groups['masters']
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
- name: Enable kubelet service
  systemd:
    name: kubelet
    enabled: yes
    state: started

